/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutYalSidebar: typeof import('./src/components/AboutYalSidebar.vue')['default']
    AuthLayout: typeof import('./src/components/auth/AuthLayout.vue')['default']
    Breadcrumb: typeof import('./src/components/Breadcrumb.vue')['default']
    Carousel: typeof import('./src/components/Carousel/Carousel.vue')['default']
    CarouselControls: typeof import('./src/components/CarouselControls.vue')['default']
    CarouselIndicators: typeof import('./src/components/Carousel/CarouselIndicators.vue')['default']
    CommentList: typeof import('./src/components/CommentList.vue')['default']
    ConfirmModal: typeof import('./src/components/common/ConfirmModal.vue')['default']
    Drawer: typeof import('./src/components/Drawer.vue')['default']
    IconLucideShoppingBag: typeof import('~icons/lucide/shopping-bag')['default']
    ImageUpload: typeof import('./src/components/ImageUpload.vue')['default']
    InteractiveCard: typeof import('./src/components/CorporationMission/InteractiveCard.vue')['default']
    InvoiceCard: typeof import('./src/components/orders/InvoiceCard.vue')['default']
    LoginInput: typeof import('./src/components/auth/LoginInput.vue')['default']
    LogisticsCard: typeof import('./src/components/orders/LogisticsCard.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    OrderActionsBar: typeof import('./src/components/orders/OrderActionsBar.vue')['default']
    OrderAmount: typeof import('./src/components/orders/OrderAmount.vue')['default']
    OrderAmountSummary: typeof import('./src/components/orders/OrderAmountSummary.vue')['default']
    OrderCard: typeof import('./src/components/orders/OrderCard.vue')['default']
    OrderCommentBlock: typeof import('./src/components/orders/OrderCommentBlock.vue')['default']
    OrderItemRow: typeof import('./src/components/orders/OrderItemRow.vue')['default']
    OrderReview: typeof import('./src/components/review/OrderReview.vue')['default']
    OrderStatusTimeline: typeof import('./src/components/orders/OrderStatusTimeline.vue')['default']
    PaymentInfoCard: typeof import('./src/components/orders/PaymentInfoCard.vue')['default']
    PaymentMethodCard: typeof import('./src/components/orders/PaymentMethodCard.vue')['default']
    ProductCard: typeof import('./src/components/ProductCard.vue')['default']
    ProductReviews: typeof import('./src/components/review/ProductReviews.vue')['default']
    ProgressCircle: typeof import('./src/components/Carousel/ProgressCircle.vue')['default']
    QuillEditor: typeof import('./src/components/editor/QuillEditor.vue')['default']
    ReviewEmpty: typeof import('./src/components/review/states/ReviewEmpty.vue')['default']
    ReviewFilters: typeof import('./src/components/review/blocks/ReviewFilters.vue')['default']
    ReviewItem: typeof import('./src/components/review/items/ReviewItem.vue')['default']
    ReviewList: typeof import('./src/components/review/blocks/ReviewList.vue')['default']
    ReviewMedia: typeof import('./src/components/review/items/ReviewMedia.vue')['default']
    ReviewReplyBlock: typeof import('./src/components/review/blocks/ReviewReplyBlock.vue')['default']
    ReviewStats: typeof import('./src/components/review/blocks/ReviewStats.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShippingProtection: typeof import('./src/components/ShippingProtection.vue')['default']
    ShippingProtectionIcon: typeof import('./src/components/icons/ShippingProtectionIcon.vue')['default']
    SimilarProducts: typeof import('./src/components/SimilarProducts.vue')['default']
    SustainableCraftsmanshipCard: typeof import('./src/components/CorporationMission/SustainableCraftsmanshipCard.vue')['default']
  }
}
