/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutYalSidebar: typeof import('./src/components/AboutYalSidebar.vue')['default']
    Carousel: typeof import('./src/components/Carousel/Carousel.vue')['default']
    CarouselControls: typeof import('./src/components/CarouselControls.vue')['default']
    CarouselIndicators: typeof import('./src/components/Carousel/CarouselIndicators.vue')['default']
    ContentPage: typeof import('./src/components/admin/ContentPage.vue')['default']
    DebugInfo: typeof import('./src/components/DebugInfo.vue')['default']
    Drawer: typeof import('./src/components/Drawer.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconLucideShoppingBag: typeof import('~icons/lucide/shopping-bag')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    ImageUpload: typeof import('./src/components/ImageUpload.vue')['default']
    InteractiveCard: typeof import('./src/components/CorporationMission/InteractiveCard.vue')['default']
    LoginInput: typeof import('./src/components/login/LoginInput.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    ProductCard: typeof import('./src/components/ProductCard.vue')['default']
    ProgressCircle: typeof import('./src/components/Carousel/ProgressCircle.vue')['default']
    QuillEditor: typeof import('./src/components/editor/QuillEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShippingProtectionIcon: typeof import('./src/components/icons/ShippingProtectionIcon.vue')['default']
    SimilarProducts: typeof import('./src/components/SimilarProducts.vue')['default']
    SustainableCraftsmanshipCard: typeof import('./src/components/CorporationMission/SustainableCraftsmanshipCard.vue')['default']
  }
}
